name: ${project.name}
version: ${project.version}
description: ${project.description}
author: [piratjsk, _an0 (sqlite system)]

main: net.piratjsk.portals.Portals

commands:
   portals:
      description: Shows the number of active portals.
      aliases: [portal,portale]
